name: Spotify Clone CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t spotify-backend ~/backend_project

      - name: Deploy to Production via Ansible
        run: |
          ansible-playbook -i ~/hosts.ini ~/deploy_spotify_prod.yml

# Demo pour le prof
